required-players: 10
countdown-seconds: 30
lobby-spawn:
  world: 'world'
    x: 100
    y: 100
    z: 100
    pitch: 60
    yaw: 60
arenas:
  '0':
    spawn:
      world: 'world'
      x: 100
      y: 100
      z: 100
      pitch: 100
      yaw: 100
  '1':
    spawn:
      world: 'world'
      x: 100
      y: 100
      z: 100
      pitch: 100
      yaw: 100